version: 2.1 # use CircleCI 2.1

jobs:
  node-latest: &test
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.8.0
    steps:

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm ci --cache .npm --prefer-offline

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm

      - run: sudo npm link # make the command executable directly from the command line

      # Run tests:
      - run:
          name: test
          command: npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always

      # Run linter:
      - run:
          name: lint
          command: npm run lint -- --format junit --output-file ./reports/eslint/eslint.xml
          when: always

      # Upload results:
      - store_test_results:
          path: reports

      - store_artifacts:
          path: ./reports/mocha/test-results.xml

      - store_artifacts:
          path: ./reports/eslint/eslint.xml

  node-14:
    <<: *test
    docker:
      - image: circleci/node:14.0.0
  node-13:
    <<: *test
    docker:
      - image: circleci/node:13.13.0
  node-12:
    <<: *test
    docker:
      - image: circleci/node:12.16.2
  node-10:
    <<: *test
    docker:
      - image: circleci/node:10.20.1
  node-8:
    <<: *test
    docker:
      - image: circleci/node:8.17.0

workflows:
  version: 2
  "cmd-to-json":
    jobs:
      - node-latest
      - node-14
      - node-12
      - node-13
      - node-10
      - node-8
